@URL_DEV = http://localhost:3000/v1/api

// Signup
POST {{URL_DEV}}/shop/signup
Content-Type: application/json
x-api-key: 4168a193eb36985e7f9da5a77c315c46aae5f7d5c4dcb2b4f32290ec47fbcbad49ed89b0551dfd5c1eed36ccc7b72bf92a210114cd584e77f72a71da8a845c27

{
    "name": "James Tran",
    "email": "trannamhai.dn@gmail.com",
    "password": "namvip123"
}